MetaDataFormat: yaml
baseURL: 'https://scholz.ruhr/'
languageCode: en-us
defaultContentLanguage: en
title: scholz.ruhr
theme: scholz.ruhr-theme
enableRobotsTXT: true
canonifyURLs: true
pygmentsUseClasses: true
taxonomies: {}
params:
  title: Merlin Scholz
  blogTitle: Merlin Scholz's Blog
  description: Merlin Scholz's Blog
  author: Merlin Scholz
outputs:
  home:
    - HTML
    - RSS
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4
menu:
  header:
  
  social:
    - name: Github
      url: 'https://github.com/merlinscholz/'
      weight: 1
    - name: Twitter
      url: 'https://twitter.com/ruhrscholz'
      weight: 2
  article:
    - name: Home
      url: /
      weight: 1
    - name: Go Up
      url: '#'
      weight: 2
privacy:
  twitter:
    simple: true
services:
  twitter:
    disableInlineCSS: true
