baseURL = "https://mscholz.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mscholz.dev"
theme = "mscholz.dev-theme"
enableRobotsTXT = true
canonifyURLs = true
paginate = 20
disqusShortname = "mscholz"
GoogleAnalytics="UA-47277692-7"

[taxonomies]
    tag = "tags"

[params]
    description = "Trying to make sense of modern technology"
    mainSections = ["post"]
    author = "Merlin Scholz"


[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 5

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 20

    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 30

    [[menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/mscholz_dev"
        weight = 40

    [[menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/mscholz-dev"
        weight = 50

[outputs]
	home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4
