baseURL = "https://mscholz.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mscholz.dev"
theme = "twentynineteen"
enableRobotsTXT = true
canonifyURLs = true
paginate = 5
googleAnalytics = "UA-47277692-7"

[taxonomies]
    tag = "tags"

[params]
description = "Trying to make sense of modern technology"
author = "Merlin Scholz"

accent_color = "#ff2200" # Set a custom accent color for links and image filters, if enabled. Defaults to blue.
#privacy_link = "/privacy/" # Relative URL to privacy page, if there is one. This enables a Privacy Policy link in the footer. The link doesn't display if this isn't specified.
disable_image_filters = false # Setting to true disables the color filter feature on images. Defaults to false.

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 20

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 30


    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "http://localhost:1313/index.xml"
        weight = 40

    [[menu.social]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/mscholz-dev"

    [[menu.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/mscholz_dev"

    [[menu.footer]]
        name = "Back to top"
        url = "#"
        weight = 4
[outputs]
	home = ["HTML", "RSS", "JSON"]
