baseURL = "https://merlinscholz.name/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Merlin Scholz"
theme = "merlinscholz.name-theme"
enableRobotsTXT = true
canonifyURLs = true
paginate = 9999
pygmentsUseClasses=true

[taxonomies]

[params]
    title = "merlinscholz.name"
    description = "Trying to make sense of modern technology"
    author = "Merlin Scholz"

[outputs]
	home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4