baseURL = "https://mscholz.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mscholz.dev"
theme = "casper3plus"
enableRobotsTXT = true
canonifyURLs = true
paginate = 5

# hugo special directories. generally do *not* need to modify these
contentdir = "content"
dataDir = "data"
defaultLayout = "post"
layoutdir = "layouts"
paginatePath = "page"
publishdir = "public"
staticdir = "static"
themesdir = "themes"

[taxonomies]
    tag = "tags"

[params]
    analytics = "UA-47277692-7"
    description = "Trying to make sense of modern technology"
    mainSections = ["post"]
    author = "Merlin Scholz"
    hideHUGOSupport = true
    github = "https://github.com/mscholz-dev"
    twitter = "https://twitter.com/mscholz_dev"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 5

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 20

    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 30

[outputs]
	home = ["HTML", "RSS"]
