baseURL = "https://merlinscholz.name/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Merlin Scholz"
theme = "merlinscholz.name-theme"
enableRobotsTXT = true
canonifyURLs = true
paginate = 9999
pygmentsUseClasses=true

[taxonomies]

[params]
    title = "Merlin Scholz"
    blogTitle = "Merlin Scholz's Blog"
    description = "Trying to make sense of modern technology"
    author = "Merlin Scholz"

[outputs]
	home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

[menu]
  [[menu.social]]
    name = "Github"
    url = "https://github.com/merlinscholz/"
    weight = 1
  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/mscholz_dev"
    weight = 2
  [[menu.social]]
    name = "Hacker News"
    url = "https://news.ycombinator.com/user?id=merlinscholz"
    weight = 3
  [[menu.social]]
    name = "Keybase"
    url = "https://keybase.io/merlinscholz"
    weight = 4
  [[menu.social]]
    name = "Ko-fi"
    url = "https://ko-fi.com/merlinscholz"
    weight = 5
    
  [[menu.article]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.article]]
    name = "Go Up"
    url = "#"
    weight = 2

[privacy]
  [privacy.twitter]
    simple = true

[services]
  [services.twitter]
    disableInlineCSS = true