[build]
  base = "/"
  publish = "public/"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  # TODO Caching, GZIP